### ISSUE TITLE
Bipartite Algorithm causes the program to freeze when the graph order and size gets large (I swear it happens)

### ISSUE THREAD

**Issue by JimmyJamJr** [cs425-t11-2021/graph-it#92]

**Comment by JimmyJamJr** [comment]
Caused by race conditions as a result of the main thread and Chromatic thread accessing the Graph adjacency dictionary at the same time.

**Comment by dianedu** [comment]
not sure which algorithm causes this, but my program did freeze

**Comment by JimmyJamJr** [comment]
Sufficiently addressed
